var stocks = [
	{
		StockNumber: "789-00010273",
		AssignmentType: "Standard",
		VehicleStatus: "Remit Entered",
		AssignDateTime: "4/29/2004 8:00:00 AM",
		LastVin: "101084", 
		DestinationLocation: "Jackson", 
		Assignor: "Christopher Black", 
		SalvageProvider: "Safeway Insurance - Mississippi - ACH", 
		ClaimNumber: "789462", 
		PolicyNumber: "41598", 
		OwnerLastName: "Johnson", 
		xtra: "info"
	},
	{
		StockNumber: "465-00010274",
		AssignmentType: "Standard",
		VehicleStatus: "Remit Entered",
		AssignDateTime: "4/29/2004 8:00:00 AM",
		LastVin: "101084", 
		DestinationLocation: "Aurora", 
		Assignor: "Dave Patton", 
		SalvageProvider: "Safeway Insurance - Mississippi - ACH", 
		ClaimNumber: "034123", 
		PolicyNumber: "23456", 
		OwnerLastName: "Johnson", 
		xtra: "info"
	},
	{
		StockNumber: "123-00010275",
		AssignmentType: "Standard",
		VehicleStatus: "Remit Entered",
		AssignDateTime: "4/29/2004 8:00:00 AM",
		LastVin: "101084", 
		DestinationLocation: "Jackson", 
		Assignor: "Jerry Patton", 
		SalvageProvider: "Safeway Insurance - Mississippi - ACH", 
		ClaimNumber: "034462", 
		PolicyNumber: "87654", 
		OwnerLastName: "Johnson", 
		xtra: "info"
	},
	{
		StockNumber: "425-07890276",
		AssignmentType: "Standard",
		VehicleStatus: "Remit Entered",
		AssignDateTime: "4/29/2004 8:00:00 AM",
		LastVin: "101084", 
		DestinationLocation: "Jackson", 
		Assignor: "Jerry Patton", 
		SalvageProvider: "Safeway Insurance - Mississippi - ACH", 
		ClaimNumber: "159462", 
		PolicyNumber: "12387", 
		OwnerLastName: "Johnson", 
		xtra: "info"
	},
	{
		StockNumber: "425-00012377",
		AssignmentType: "Standard",
		VehicleStatus: "Remit Entered",
		AssignDateTime: "4/29/2004 8:00:00 AM",
		LastVin: "101084", 
		DestinationLocation: "Jackson", 
		Assignor: "Jerry Patton", 
		SalvageProvider: "Safeway Insurance - Mississippi - ACH", 
		ClaimNumber: "034462", 
		PolicyNumber: "09876", 
		OwnerLastName: "Phillips", 
		xtra: "info" 
	},
	{
		StockNumber: "159-15910278",
		AssignmentType: "Non Standard",
		VehicleStatus: "Remit Entered",
		AssignDateTime: "4/29/2004 8:00:00 AM",
		LastVin: "101084", 
		DestinationLocation: "Jackson", 
		Assignor: "Jerry Patton", 
		SalvageProvider: "Safeway Insurance - Mississippi - ACH", 
		ClaimNumber: "034462", 
		PolicyNumber: "34567", 
		OwnerLastName: "Davidson", 
		xtra: "info"
	},
	{
		StockNumber: "425-00010279",
		AssignmentType: "Non Standard",
		VehicleStatus: "Remit Entered",
		AssignDateTime: "7/29/2003 9:32:41 AM",
		LastVin: "101084", 
		DestinationLocation: "Jackson", 
		Assignor: "Jerry Patton", 
		SalvageProvider: "Safeway Insurance - Mississippi - ACH", 
		ClaimNumber: "034462", 
		PolicyNumber: "15243", 
		OwnerLastName: "Matthews", 
		xtra: "info"
	},
	{
		StockNumber: "425-00010280",
		AssignmentType: "Standard",
		VehicleStatus: "Remit Entered",
		AssignDateTime: "4/29/2004 8:00:00 AM",
		LastVin: "101084", 
		DestinationLocation: "Jackson", 
		Assignor: "John Doe", 
		SalvageProvider: "Safeway Insurance - Mississippi - ACH", 
		ClaimNumber: "034462", 
		PolicyNumber: "98762", 
		OwnerLastName: "Shoe", 
		xtra: "info"
	},
	{
		StockNumber: "425-00010280",
		AssignmentType: "Standard",
		VehicleStatus: "Remit Entered",
		AssignDateTime: "4/29/2004 8:00:00 AM",
		LastVin: "101084", 
		DestinationLocation: "Jackson", 
		Assignor: "Jerry Patton", 
		SalvageProvider: "Safeway Insurance - Mississippi - ACH", 
		ClaimNumber: "034462", 
		PolicyNumber: "23458", 
		OwnerLastName: "Taryguy", 
		xtra: "info"
	},
	{
		StockNumber: "425-00010280",
		AssignmentType: "Standard",
		VehicleStatus: "Remit Entered",
		AssignDateTime: "4/29/2004 8:00:00 AM",
		LastVin: "101084", 
		DestinationLocation: "Jackson", 
		Assignor: "Jerry Patton", 
		SalvageProvider: "Safeway Insurance - Mississippi - ACH", 
		ClaimNumber: "034462", 
		PolicyNumber: "15678", 
		OwnerLastName: "Hodor", 
		xtra: "info"
	},
	{
		StockNumber: "425-00010280",
		AssignmentType: "Standard",
		VehicleStatus: "Remit Entered",
		AssignDateTime: "4/29/2004 8:00:00 AM",
		LastVin: "101084", 
		DestinationLocation: "Jackson", 
		Assignor: "Jerry Patton", 
		SalvageProvider: "Safeway Insurance - Mississippi - ACH", 
		ClaimNumber: "034462", 
		PolicyNumber: "87523", 
		OwnerLastName: "Jackson", 
		xtra: "info"
	}
];